desc = "extended precision floating point types using value pairs"
keywords = ["floating-point", "doubledouble", "extended-precision", "accuracy", "precision"]
name = "DoubleFloats"
uuid = "497a8b3b-efae-58df-a0af-a86822472b78"
repo = "https://github.com/JuliaMath/DoubleFloats.jl.git"
license = "MIT"
version = "0.9.1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
GenericSVD = "01680d73-4ee2-5a08-a1aa-533608c188bb"
GenericSchur = "c145ed77-6b09-5dd9-b285-bf645a82121e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[extras]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SpecialFunctions"]

[compat]
GenericSVD = "0"
GenericSchur = "0"
Polynomials = "0"
SpecialFunctions = "0"
Quadmath = "0"
julia = "1"
